Insert into State (fromState, toState, message, isWide) values (1, 1, 'Мои сериалы', 1);
Insert into State (fromState, toState, message, isWide) values (1, 1, 'Вы ещё не подписаны ни на один сериал', 4);
Insert into State (fromState, toState, message, isWide) values (1, 2, 'Сериалы, на которые Вы подписаны', 4);
Insert into State (fromState, toState, message, isWide) values (1, 7, 'Все сериалы', 1);
Insert into State (fromState, toState, message, isWide) values (1, 7, 'Сериалы, на которые Вы можете подписаться', 4);
Insert into State (fromState, toState, message, isWide) values (2, 1, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (2, 1, 'Список каких сериалов Вы хотите увидеть?', 4);
Insert into State (fromState, toState, message, isWide) values (2, 4, 'Myseries', -4);
Insert into State (fromState, toState, message, isWide, action) values (2, 4, '###seriesname subscribed', -1, 7);
Insert into State (fromState, toState, message, isWide) values (4, 2, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (4, 2, 'Сериалы, на которые Вы подписаны', 4);
Insert into State (fromState, toState, message, isWide, action) values (4, 1, 'Отписаться от сериала', 1, 1);
Insert into State (fromState, toState, message, isWide) values (4, 6, 'Предложить озвучку', 1);
Insert into State (fromState, toState, message, isWide) values (4, 6, 'Напишите, какую озвучку Вы бы хотели', 4);
Insert into State (fromState, toState, message, isWide, action) values (6, 1, 'Назад', 0, 6);
Insert into State (fromState, toState, message, isWide, action) values (6, 1, '###anymessage', -1, 3);
Insert into State (fromState, toState, message, isWide, action) values (4, 1, '###translationname', -1, 5);
Insert into State (fromState, toState, message, isWide) values (4, 1, 'Alltranslations', -3);
Insert into State (fromState, toState, message, isWide) values (5, 4, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (5, 4, 'Выберите озвучку', 4);
Insert into State (fromState, toState, message, isWide, action) values (5, 1, 'Отписаться', 0, 4);
Insert into State (fromState, toState, message, isWide) values (7, 1, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (7, 1, 'Список каких сериалов Вы хотите увидеть?', 4);
Insert into State (fromState, toState, message, isWide) values (7, 3, 'Предложить сериал', 1);
Insert into State (fromState, toState, message, isWide) values (7, 3, 'Напишите, какую сериал Вы бы хотели', 4);
Insert into State (fromState, toState, message, isWide) values (3, 7, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (3, 7, 'Сериалы, на которые Вы можете подписаться', 0);
Insert into State (fromState, toState, message, isWide, action) values (3, 1, '###anymessage', -1, 2);
Insert into State (fromState, toState, message, isWide) values (7, 8, 'Allseries', -2);
Insert into State (fromState, toState, message, isWide, action) values (7, 4, '###seriesname subscribed', -1, 7);
Insert into State (fromState, toState, message, isWide) values (8, 7, 'Назад', 0);
Insert into State (fromState, toState, message, isWide) values (8, 7, 'Выберите сериал', 4);
Insert into State (fromState, toState, message, isWide) values (8, 6, 'Предложить озвучку', 1);
Insert into State (fromState, toState, message, isWide) values (8, 6, 'Напишите, какую озвучку Вы бы хотели', 4);
Insert into State (fromState, toState, message, isWide, action) values (8, 1, '###translationname', -1, 5);
Insert into State (fromState, toState, message, isWide) values (8, 1, 'Alltranslations', -3);